POST http://localhost:3003/api/login
Content-Type:  application/json

{
"username":"mluukkai",
"name": "Superuser",
"password":"salainen"
}

###
POST http://localhost:3003/api/blogs
Content-Type:  application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI2NmZkM2Y5NTAzMjU5ZTdlMTEzODE5MWMiLCJpYXQiOjE3Mjc5NDg0OTYsImV4cCI6MTcyNzk1MjA5Nn0.mQeeOZ6_1BFu3Sh2AHmTXMXvlP7WpkVzff-By7p9dEQ

{
  "title": "Hello From Token2",
  "author": "Shelbean",
  "url": "Hello",
  "likes": 100,
}

###
POST http://localhost:3003/api/blogs
Content-Type:  application/json

{
    "title": "React patterns",
    "author": "Michael Chan",
    "url": "https://reactpatterns.com/",
    "likes": 7,
    "userId": "66fd3fd703259e7e1138191e"
}

###
POST http://localhost:3003/api/blogs
Content-Type:  application/json

{
    "title": "Go To Statement Considered Harmful",
    "author": "Edsger W. Dijkstra",
    "url": "http://www.u.arizona.edu/~rubinson/copyright_violations/Go_To_Considered_Harmful.html",
    "likes": 5,
    "userId": "66fd3fd703259e7e1138191e"
}

###
POST http://localhost:3003/api/blogs
Content-Type:  application/json

{
    "title": "Canonical string reduction",
    "author": "Edsger W. Dijkstra",
    "url": "http://www.cs.utexas.edu/~EWD/transcriptions/EWD08xx/EWD808.html",
    "likes": 12,
    "userId": "66fe275ecd2e6a4eb795fff6"
}

### 
DELETE http://localhost:3003/api/blogs/66fe6a07eaddbf5139a25ee2
Content-Type:  application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI2NmZkM2Y5NTAzMjU5ZTdlMTEzODE5MWMiLCJpYXQiOjE3Mjc5NDg0OTYsImV4cCI6MTcyNzk1MjA5Nn0.mQeeOZ6_1BFu3Sh2AHmTXMXvlP7WpkVzff-By7p9dEQ

###
PUT http://localhost:3003/api/blogs/66fe2cd29d7607b1a022ed86
Content-Type:  application/json

{
    "title": "Hello",
    "author": "Shelbean",
    "url": "Hello",
    "likes": 99,
    "user": "66fd3f9503259e7e1138191c",
    "id": "66fe2cd29d7607b1a022ed86"
}
###
PUT http://localhost:3003/api/blogs/66fe2cd29d7607b1a022ed86/comments
Content-Type:  application/json

{
    "comment": "awsome"
}